- image: product-1.jpg
  name: Container for a Fanta

- image: product-2.jpg
  name: Strange sunglasses

- image: product-3.jpg
  name: Pen Pineapple Apple Pen

- image: product-4.jpg
  name: Binoculars

- image: product-5.jpg
  name: Magical notebook

- image: product-6.jpg
  name: Dragonfly eyes

- image: product-7.jpg
  name: Fireman's pipe

- image: product-8.jpg
  name: Garden shears

- image: product-9.jpg
  name: Ironman wallet

- image: product-10.jpg
  name: Blue notebook

- image: product-11.jpg
  name: Morning alarm clock

- image: product-12.jpg
  name: Spy camera

- image: product-13.jpg
  name: Housefly
