core:
  - changed-files:
      - any-glob-to-any-file: 'core/**'

preview:
  - changed-files:
      - any-glob-to-any-file: 'preview/**'

docs:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'

shared:
  - changed-files:
      - any-glob-to-any-file: 'shared/**'

scss:
  - changed-files:
      - any-glob-to-any-file:
          - 'core/scss/**'
          - 'preview/scss/**'
          - 'docs/scss/**'

javascript:
  - changed-files:
      - any-glob-to-any-file:
          - 'core/js/**'
          - 'preview/js/**'

icons:
  - changed-files:
      - any-glob-to-any-file:
          - 'shared/data/icons.json'
          - 'shared/data/icons-info.json'
          - 'docs/content/icons/**'

illustrations:
  - changed-files:
      - any-glob-to-any-file:
          - 'shared/static/illustrations/**'
          - 'shared/data/illustrations.json'
          - 'docs/content/illustrations/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - '**/package.json'
          - 'pnpm-lock.yaml'
