---
version: "3.3"
services:

  tabler:
    image: tabler
    container_name: tabler
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./src:/app/src
      - ./_config.yml:/app/_config.yml
    tty: true
