---
services:

  tabler:
    image: tabler
    container_name: tabler
    build: .
    ports:
      - 3000:3000
      - 3010:3010
    volumes:
      - ./core:/app/core
      - ./preview:/app/preview
      - ./docs:/app/docs
      - ./shared:/app/shared
      # keep the node_modules installed in the image (not overwritten by the mounts)
      - /app/core/node_modules
      - /app/preview/node_modules
      - /app/docs/node_modules
    tty: true
