packages:
  - core
  - preview
  - docs
  - shared

overrides:
  brace-expansion: '>=5.0.8'
  sharp: '>=0.35.0'
  svgo: '>=4.0.2'

allowBuilds:
  '@parcel/watcher': false
  core-js: false
  core-js-pure: false
  esbuild: false
  sharp: false

minimumReleaseAge: 1440
