packages:
  - core
  - preview
  - preview-astro
  - docs
  - docs-astro
  - shared

allowBuilds:
  '@parcel/watcher': false
  core-js: false
  core-js-pure: false
  esbuild: false
  sharp: false

minimumReleaseAge: 1440
