// Generated from the core SCSS maps by .build/generate-tokens.ts — DO NOT EDIT.
// Regenerate with: pnpm run generate-tokens

/** Keys of `$theme-colors` (core/scss/_variables.scss). */
export const themeColors = ['primary', 'secondary', 'success', 'info', 'warning', 'danger', 'light', 'dark', 'muted', 'blue', 'azure', 'indigo', 'purple', 'pink', 'red', 'orange', 'yellow', 'lime', 'green', 'teal', 'cyan'] as const
export type ThemeColor = (typeof themeColors)[number]

/** Keys of `$social-colors` (core/scss/_variables.scss). */
export const socialColors = ['x', 'facebook', 'twitter', 'linkedin', 'google', 'youtube', 'vimeo', 'dribbble', 'github', 'instagram', 'pinterest', 'vk', 'rss', 'flickr', 'bitbucket', 'tabler'] as const
export type SocialColor = (typeof socialColors)[number]

/** Keys of `$avatar-sizes` (core/scss/_variables.scss). */
export const avatarSizes = ['xxs', 'xs', 'sm', 'md', 'lg', 'xl', '2xl'] as const
export type AvatarSize = (typeof avatarSizes)[number]

/** Keys of `$aspect-ratios` (core/scss/_variables.scss). */
export const aspectRatios = ['1x1', '2x1', '1x2', '3x1', '1x3', '4x1', '1x4', '4x3', '3x4', '16x9', '9x16', '21x9', '9x21'] as const
export type AspectRatio = (typeof aspectRatios)[number]

/** Keys of `$grid-breakpoints` (core/scss/_settings.scss). */
export const breakpoints = ['xs', 'sm', 'md', 'lg', 'xl', 'xxl'] as const
export type Breakpoint = (typeof breakpoints)[number]

/** Keys of `$breadcrumb-variants` (core/scss/_variables.scss). */
export const breadcrumbVariants = ['dots', 'arrows', 'bullets'] as const
export type BreadcrumbVariant = (typeof breadcrumbVariants)[number]

/** Keys of `$form-validation-states` (core/scss/_variables.scss). */
export const formValidationStates = ['valid', 'invalid'] as const
export type FormValidationState = (typeof formValidationStates)[number]

/** Keys of `$payment-providers` (core/scss/_variables.scss). */
export const paymentProviders = [
  '2c2p',
  '2checkout',
  'adyen',
  'affirm',
  'alipay-plus',
  'alipay',
  'allegro-pay',
  'amazon-pay',
  'amazon',
  'americanexpress',
  'applepay',
  'authorize',
  'autopay',
  'bancontact',
  'binance-usd',
  'bitcoin',
  'bitpay',
  'bkash',
  'blik',
  'braintree',
  'cash-app',
  'chime',
  'cirrus',
  'clickandbuy',
  'coinkite',
  'dinersclub',
  'directdebit',
  'discover',
  'dotpay',
  'dwolla',
  'easypaisa',
  'ebay',
  'elo',
  'epayco',
  'esewa',
  'ethereum',
  'eway',
  'fonepay',
  'giropay',
  'google-pay',
  'googlewallet',
  'hubspot',
  'ingenico',
  'ideal',
  'imepay',
  'jcb',
  'khalti',
  'klarna',
  'laser',
  'litecoin',
  'maestro',
  'mastercard',
  'mercado-pago',
  'metamask',
  'mir',
  'monero',
  'moneygram',
  'neteller',
  'ogone',
  'okpay',
  'opensea',
  'paybox',
  'payconiq',
  'payka',
  'payline',
  'paymill',
  'payone',
  'payoneer',
  'paypal',
  'paypo',
  'paysafe',
  'paysafecard',
  'payu',
  'payza',
  'poli',
  'przelewy24',
  'revolut-pay',
  'ripple',
  'sage',
  'samsung-pay',
  'sepa',
  'shop-pay',
  'shopify',
  'skrill',
  'solana',
  'solo',
  'spingo',
  'square',
  'stax',
  'stripe',
  'switch',
  'tether',
  'tpay',
  'troy',
  'true-usd',
  'ukash',
  'unionpay',
  'venmo',
  'verifone',
  'verisign',
  'visa',
  'we-chat-pay',
  'webmoney',
  'westernunion',
  'wise',
  'worldpay',
  'zelle',
] as const
export type PaymentProvider = (typeof paymentProviders)[number]

/** Keys of `$flag-countries` (core/scss/_variables.scss). */
export const flagCountries = [
  'ad',
  'af',
  'ae',
  'afrun',
  'ag',
  'ai',
  'al',
  'am',
  'ao',
  'aq',
  'ar',
  'as',
  'at',
  'au',
  'aw',
  'ax',
  'az',
  'ba',
  'bb',
  'bd',
  'be',
  'bf',
  'bg',
  'bh',
  'bi',
  'bj',
  'bl',
  'bm',
  'bn',
  'bo',
  'bq-bo',
  'bq-sa',
  'bq-se',
  'br',
  'bs',
  'bt',
  'bv',
  'bw',
  'by',
  'bz',
  'ca',
  'cc',
  'cd',
  'cf',
  'cg',
  'ch',
  'ci',
  'ck',
  'cl',
  'cm',
  'cn',
  'co',
  'cr',
  'cu',
  'cv',
  'cw',
  'cx',
  'cy',
  'cz',
  'de',
  'dj',
  'dk',
  'dm',
  'do',
  'dz',
  'ec',
  'ee',
  'eg',
  'eh',
  'er',
  'es',
  'et',
  'eu',
  'fi',
  'fj',
  'fk',
  'fm',
  'fo',
  'fr',
  'ga',
  'gb-eng',
  'gb-sct',
  'gb',
  'gb-wls',
  'gb-nir',
  'gd',
  'ge',
  'gf',
  'gg',
  'gh',
  'gi',
  'gl',
  'gm',
  'gn',
  'gp',
  'gq',
  'gr',
  'gs',
  'gt',
  'gu',
  'gw',
  'gy',
  'hk',
  'hm',
  'hn',
  'hr',
  'ht',
  'hu',
  'id',
  'ie',
  'il',
  'im',
  'in',
  'io',
  'iq',
  'ir',
  'is',
  'it',
  'je',
  'jm',
  'jo',
  'jp',
  'ke',
  'kg',
  'kh',
  'ki',
  'km',
  'kn',
  'kp',
  'kr',
  'kw',
  'ky',
  'kz',
  'la',
  'lb',
  'lc',
  'li',
  'lk',
  'lr',
  'ls',
  'lt',
  'lu',
  'lv',
  'ly',
  'ma',
  'mc',
  'md',
  'me',
  'mf',
  'mg',
  'mh',
  'mk',
  'ml',
  'mm',
  'mn',
  'mo',
  'mp',
  'mq',
  'mr',
  'ms',
  'mt',
  'mu',
  'mv',
  'mw',
  'mx',
  'my',
  'mz',
  'na',
  'nc',
  'ne',
  'nf',
  'ng',
  'ni',
  'nl',
  'no',
  'np',
  'nr',
  'nu',
  'nz',
  'om',
  'pa',
  'pe',
  'pf',
  'pg',
  'ph',
  'pk',
  'pl',
  'pm',
  'pn',
  'pr',
  'ps',
  'pt',
  'pw',
  'py',
  'qa',
  'rainbow',
  're',
  'ro',
  'rs',
  'ru',
  'rw',
  'sa',
  'sb',
  'sc',
  'sd',
  'se',
  'sg',
  'sh',
  'si',
  'sj',
  'sk',
  'sl',
  'sm',
  'sn',
  'so',
  'sr',
  'ss',
  'st',
  'sv',
  'sx',
  'sy',
  'sz',
  'tc',
  'td',
  'tf',
  'tg',
  'th',
  'tj',
  'tk',
  'tl',
  'tm',
  'tn',
  'to',
  'tr',
  'tt',
  'tv',
  'tw',
  'tz',
  'ua',
  'ug',
  'um',
  'unasur',
  'us',
  'uy',
  'uz',
  'va',
  'vc',
  've',
  'vg',
  'vi',
  'vn',
  'vu',
  'wf',
  'ws',
  'ye',
  'za',
  'zm',
  'zw',
] as const
export type FlagCountry = (typeof flagCountries)[number]

/** Keys of `$sizes` (core/scss/ui/_patterns.scss). */
export const patternSizes = ['sm', 'md', 'lg', 'xl'] as const
export type PatternSize = (typeof patternSizes)[number]
