name: Build

on:
  pull_request: null
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Set up the workspace
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps chromium

      - name: Check rendered html
        run: pnpm run check-html preview/dist docs/dist --quiet

      - name: Check markup classes
        run: pnpm run check-markup-classes --html preview/dist --html docs/dist --css preview/dist/dist/css --css preview/dist/dist/libs --css preview/dist/preview/css --css docs/dist/css --css docs/dist/preview/css
