name: JS Tests

on:
  pull_request: null
  push:
    branches:
      - dev
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Chromium
        run: pnpm exec playwright install --with-deps chromium
        working-directory: core

      - name: Run tests
        run: pnpm --filter @tabler/core test
